=== kalliekon/CineVerse_SW_MD/cinema.dtd
<!ELEMENT cinema (directors, movies, awards)>
<!ELEMENT directors (director+)>
<!ELEMENT director (name, birthDate?, nationality*, bio?, awardsRef?, deathYear?)>
<!ATTLIST director      
	id		ID					#REQUIRED
	status	(alive|deceased)	#IMPLIED
>
<!ELEMENT name (#PCDATA)>
<!ELEMENT birthDate (#PCDATA)>
<!ELEMENT nationality (#PCDATA)>
<!ELEMENT bio (#PCDATA)>
<!ELEMENT awardsRef EMPTY>
<!ATTLIST awardsRef   
	refs	IDREFS	#REQUIRED
>
<!ELEMENT deathYear (#PCDATA)>
<!ELEMENT movies (movie+)>
<!ELEMENT movie (title, year, duration, genres, actors, production+, description?, boxOffice?, poster?, link?)>
<!ATTLIST movie          
	id			ID		#REQUIRED
	directorRef	IDREF	#REQUIRED
	type		CDATA	#FIXED "film"
>
<!ELEMENT title (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT genres (genre+)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT actors (actor+)>
<!ELEMENT actor (((actorName, characterName) | (characterName, actorName)), actorBirthDate?, actorNationality*, actorDeathYear?)>
<!ATTLIST actor      
	roleType	(lead|supporting)	#IMPLIED
	status		(alive|deceased)	#IMPLIED
>
<!ELEMENT actorName (#PCDATA)>
<!ELEMENT characterName (#PCDATA)>
<!ELEMENT actorBirthDate (#PCDATA)>
<!ELEMENT actorNationality (#PCDATA)>
<!ELEMENT actorDeathYear (#PCDATA)>
<!ELEMENT production (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT boxOffice (budget?, revenue?)>
<!ELEMENT budget (#PCDATA)>
<!ELEMENT revenue (#PCDATA)>
<!ELEMENT poster EMPTY>
<!ATTLIST poster      
	url			CDATA			#REQUIRED
	encoding	(mime|binhex)	"mime"
>
<!ELEMENT link (imdb | youtube)>
<!ELEMENT imdb EMPTY>
<!ATTLIST imdb   
	href	CDATA	#REQUIRED
>
<!ELEMENT youtube EMPTY>
<!ATTLIST youtube   
	href	CDATA	#REQUIRED
>
<!ELEMENT awards (award+)>
<!ELEMENT award (awardTitle, awardOrganization, awardCategory, awardYear, awardWork?)>
<!ATTLIST award   
	id	ID	#REQUIRED
>
<!ELEMENT awardTitle (#PCDATA)>
<!ELEMENT awardOrganization (#PCDATA)>
<!ELEMENT awardCategory (#PCDATA)>
<!ELEMENT awardYear (#PCDATA)>
<!ELEMENT awardWork (#PCDATA)>

=== kalliekon/CineVerse_SW_MD/cinema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cinema SYSTEM "cinema.dtd">
<?xml-stylesheet type="text/xsl" href="cinema.xsl"?>
<cinema>
	<directors>
		<director id="d1" status="deceased">
			<name>David Keith Lynch 
			</name>
			<nationality>American</nationality>
			<bio>He is considered one of the most significant figures in the history of cinema. He is a filmmaker, a visual artist, a musician and an actor, and his work is so distinctive that it has inspired the term “Lynchian”. </bio>
			<awardsRef refs="a1 a2"/>
			<deathYear>2025</deathYear>
		</director>
		<director id="d2" status="alive">
			<name>Alfonso Cuarón Orozco</name>
			<nationality>Mexican</nationality>
			<bio>A world-famous filmmaker with many prestigious awards. His work is known for being connected with the audience and his creativity and dedication to his projects is out of this world. </bio>
			<awardsRef refs="a3"/>
		</director>
		<director id="d3">
			<name>Steven Allan Spielberg</name>
			<birthDate>18 December 1946</birthDate>
			<nationality>American</nationality>
			<awardsRef refs="a4"/>
		</director>
		<director id="d4">
			<name>James Francis Cameron</name>
			<birthDate>16 August 1954</birthDate>
			<nationality>Canadian</nationality>
			<nationality>New Zealander</nationality>
		</director>
		<director id="d5" status="deceased">
			<name>Stanley Kubrick</name>
			<birthDate>26 July 1928</birthDate>
			<nationality>American</nationality>
			<bio>A great figure in filmmaking and photography of the post-war film industry. One the most influential filmmakers in the history of cinema. His films gained recognition for their innovative cinematography, their set design which were extensive, and dark humor.</bio>
			<deathYear>1999</deathYear>
		</director>
	</directors>
	<movies>
		<movie id="m1" directorRef="d1" type="film">
			<title>Twin Peaks: Fire Walk with Me</title>
			<year>1992</year>
			<duration>2h 15m</duration>
			<genres>
				<genre>horror</genre>
			</genres>
			<actors>
				<actor roleType="lead">
					<actorName>Sheryl Lee</actorName>
					<characterName>Laura Palmer</characterName>
					<actorNationality>American</actorNationality>
				</actor>
			</actors>
			<production>Ciby 2000</production>
			<poster url="twinpeaks.png" encoding="mime"/>
			<link>
				<imdb href="https://www.imdb.com/title/tt0105665/"/>
			</link>
		</movie>
		<movie id="m2" directorRef="d2" type="film">
			<title>Harry Potter and the Prisoner of Azkaban</title>
			<year>2004</year>
			<duration>2h 22m</duration>
			<genres>
				<genre>Fantasy</genre>
			</genres>
			<actors>
				<actor roleType="supporting" status="deceased">
					<actorName>Alan Sidney Patrick Rickman</actorName>
					<characterName>Severus Snape</characterName>
					<actorBirthDate>21 February 1946</actorBirthDate>
					<actorNationality>English</actorNationality>
					<actorDeathYear>2016</actorDeathYear>
				</actor>
				<actor roleType="lead">
					<characterName>Harry Potter</characterName>
					<actorName>Daniel Jacob Radcliffe</actorName>
					<actorNationality>English</actorNationality>
				</actor>
				<actor status="alive">
					<actorName>Emma Charlotte Duerre Watson</actorName>
					<characterName>Hermione Granger</characterName>
					<actorBirthDate>15 April 1990</actorBirthDate>
				</actor>
				<actor>
					<characterName>Dean Thomas</characterName>
					<actorName>Alfred Lewis Enoch</actorName>
					<actorNationality>British</actorNationality>
					<actorNationality>Brazilian</actorNationality>
				</actor>
			</actors>
			<production>Warner Bros. Pictures</production>
			<production>Heyday Films</production>
			<production>1492 Pictures</production>
			<description>Another year at Hogwarts, but this time it appears that Harry Potter has a dangerous prisoner escape hunting him. While Harry, Hermione and Ron try to find out the truth, they find themselves more shocked than they ever imagined.</description>
			<boxOffice>
				<budget>$130 million</budget>
			</boxOffice>
			<link>
				<youtube href="https://www.youtube.com/watch?v=cK2WNlj6kR0"/>
			</link>
		</movie>
		<movie id="m3" directorRef="d3" type="film">
			<title>Indiana Jones and the Kingdom of the Crystal Skull</title>
			<year>2008</year>
			<duration>2h 2m</duration>
			<genres>
				<genre>Action</genre>
				<genre>Adventure</genre>
			</genres>
			<actors>
				<actor status="alive">
					<actorName>Harrison Ford</actorName>
					<characterName>Indiana Jones</characterName>
					<actorBirthDate>13 July 1942</actorBirthDate>
				</actor>
			</actors>
			<production>Lucasfilm</production>
			<production>Paramount Pictures</production>
			<boxOffice>
				<revenue>$786.6 million</revenue>
			</boxOffice>
			<poster url="indianajones.jpg" encoding="mime"/>
			<link>
				<imdb href="https://www.imdb.com/title/tt0367882/"/>
			</link>
		</movie>
		<movie id="m4" directorRef="d4" type="film">
			<title>Titanic</title>
			<year>1997</year>
			<duration>3h 14m</duration>
			<genres>
				<genre>Romance</genre>
				<genre>Adventure</genre>
			</genres>
			<actors>
				<actor status="alive">
					<characterName>Rose Dewitt Bukater</characterName>
					<actorName>Kate Elizabeth Winslet</actorName>
					<actorBirthDate>5 October 1975</actorBirthDate>
					<actorNationality>British</actorNationality>
				</actor>
				<actor roleType="lead" status="alive">
					<actorName>Leonardo Wilhelm DiCaprio</actorName>
					<characterName>Jack Dawson</characterName>
					<actorBirthDate>11 November 1974</actorBirthDate>
				</actor>
			</actors>
			<production>Lightstorm Entertainment</production>
			<production>20th Century Fox</production>
			<production>Paramount Pictures</production>
			<description>A woman from the aristocratic society encounters a free spirited man out of her society while being on the Titanic and they form a special bond against the rules. The ship’s tragical fate though makes them fight for their survival.</description>
			<boxOffice>
				<budget>$200 million</budget>
				<revenue>$2.264 billion</revenue>
			</boxOffice>
		</movie>
		<movie id="m5" directorRef="d5">
			<title>A Clockwork Orange</title>
			<year>1971</year>
			<duration>2h 16m</duration>
			<genres>
				<genre>Sci-Fi</genre>
				<genre>Crime</genre>
				<genre>Dark Comedy</genre>
			</genres>
			<actors>
				<actor roleType="lead" status="alive">
					<actorName>Malcolm McDowell</actorName>
					<characterName>Alex DeLarge</characterName>
					<actorBirthDate>13 June 1943</actorBirthDate>
					<actorNationality>English</actorNationality>
				</actor>
				<actor roleType="lead" status="deceased">
					<actorName>Patrick Magee</actorName>
					<characterName>Mr Alexander</characterName>
					<actorBirthDate>31 March 1922</actorBirthDate>
					<actorNationality>Irish</actorNationality>
					<actorDeathYear>1982</actorDeathYear>
				</actor>
			</actors>
			<production>Polaris Productions</production>
			<production>Hawk Films</production>
			<description>A Clockwork Orange is a dystopian satire film following Alex DeLarge (Malcolm McDowell), a charismatic yet violent delinquent, who is subjected to an experimental form of state conditioning meant to reform criminals. The film explores themes of free will, morality, and the chilling consequences of a society that seeks to control human behavior.</description>
			<boxOffice>
				<budget>$1.3 million</budget>
				<revenue>$114 million</revenue>
			</boxOffice>
			<poster url="aclockworkorange.png" encoding="mime"/>
			<link>
				<imdb href="https://www.imdb.com/title/tt0066921/?ref_=nm_knf_t_2 "/>
			</link>
		</movie>
		<movie id="m6" directorRef="d5">
			<title>Full Metal Jacket</title>
			<year>1987</year>
			<duration>1h 56m</duration>
			<genres>
				<genre>Drama</genre>
				<genre>War</genre>
				<genre>Dark Comedy</genre>
			</genres>
			<actors>
				<actor roleType="lead" status="alive">
					<actorName>Matthew Modine</actorName>
					<characterName>Private Joker</characterName>
					<actorBirthDate>22 March 1959</actorBirthDate>
					<actorNationality>American</actorNationality>
				</actor>
				<actor roleType="lead" status="alive">
					<actorName>Adam Baldwin </actorName>
					<characterName>Animal Mother</characterName>
					<actorBirthDate>27 February 1962</actorBirthDate>
					<actorNationality>American</actorNationality>
				</actor>
			</actors>
			<production>Natant</production>
			<production>Harrier Films</production>
			<description>Full Metal Jacket, is a stark portrayal of U.S. Marines from the brutality of boot camp under the tyrannical Gunnery Sergeant Hartman to the psychological chaos of the Vietnam War. The film examines dehumanization, the loss of innocence, and the duality of man within a relentless military machine.­
</description>
			<boxOffice>
				<budget>$16.5–30 million</budget>
				<revenue>	$120 million</revenue>
			</boxOffice>
			<poster url="fullmetaljacket.jpg" encoding="mime"/>
			<link>
				<imdb href="https://www.imdb.com/title/tt0093058/?ref_=nm_knf_t_4 "/>
			</link>
		</movie>
	</movies>
	<awards>
		<award id="a1">
			<awardTitle>César Awards</awardTitle>
			<awardOrganization>Academy of Cinema Arts and Techniques</awardOrganization>
			<awardCategory>Best Foreign Film</awardCategory>
			<awardYear>1982</awardYear>
			<awardWork>The Elephant Man</awardWork>
		</award>
		<award id="a2">
			<awardTitle>César Awards</awardTitle>
			<awardOrganization>Academy of Cinema Arts and Techniques</awardOrganization>
			<awardCategory>Best Foreign Film</awardCategory>
			<awardYear>2002</awardYear>
			<awardWork>Mulholland Drive</awardWork>
		</award>
		<award id="a3">
			<awardTitle>BAFTA Children's Awards</awardTitle>
